experiment_name: 'experiment_regressor2'
dataset: 'train.csv'
models:
    - 'RandomForestRegressor'
    - 'LinearRegression'
    - 'ElasticNet'
    - 'SGDRegressor'
    - 'BayesianRidge'
    - 'GradientBoostingRegressor'
    - 'SVR'
    - 'KernelRidge'
x:
    - 'Id'
    - 'MSSubClass'
    - 'MSZoning'
    - 'LotArea'
    - 'Street'
    - 'Alley'
    - 'LotShape'
    - 'LandContour'
    - 'Utilities'
    - 'LotConfig'
    - 'LandSlope'
    - 'Neighborhood'
    - 'Condition1'
    - 'Condition2'
    - 'BldgType'
    - 'HouseStyle'
    - 'OverallQual'
    - 'OverallCond'
    - 'YearBuilt'
    - 'YearRemodAdd'
    - 'RoofStyle'
    - 'RoofMatl'
    - 'Exterior1st'
    - 'Exterior2nd'
    - 'MasVnrType'
    - 'MasVnrArea'
    - 'ExterQual'
    - 'ExterCond'
    - 'Foundation'
    - 'BsmtQual'
    - 'BsmtCond'
    - 'BsmtExposure'
    - 'BsmtFinType1'
    - 'BsmtFinSF1'
    - 'BsmtFinType2'
    - 'BsmtFinSF2'
    - 'BsmtUnfSF'
    - 'TotalBsmtSF'
    - 'Heating'
    - 'HeatingQC'
    - 'CentralAir'
    - 'Electrical'
    - '1stFlrSF'
    - '2ndFlrSF'
    - 'LowQualFinSF'
    - 'GrLivArea'
    - 'BsmtFullBath'
    - 'BsmtHalfBath'
    - 'FullBath'
    - 'HalfBath'
    - 'BedroomAbvGr'
    - 'KitchenAbvGr'
    - 'KitchenQual'
    - 'TotRmsAbvGrd'
    - 'Functional'
    - 'Fireplaces'
    - 'FireplaceQu'
    - 'GarageType'
    - 'GarageYrBlt'
    - 'GarageFinish'
    - 'GarageCars'
    - 'GarageArea'
    - 'GarageQual'
    - 'GarageCond'
    - 'PavedDrive'
    - 'WoodDeckSF'
    - 'OpenPorchSF'
    - 'EnclosedPorch'
    - '3SsnPorch'
    - 'ScreenPorch'
    - 'PoolArea'
    - 'PoolQC'
    - 'Fence'
    - 'MiscFeature'
    - 'MiscVal'
    - 'MoSold'
    - 'YrSold'
    - 'SaleType'
    - 'SaleCondition'
y : 
    - 'SalePrice'
models :
    ensemble:
        - 'RandomForestRegressor'
        - 'GradientBoostingRegressor'
    linear_model:
        - 'ElasticNet'
        - 'SGDRegressor'
        - 'BayesianRidge'
        - 'LinearRegression'
        #- 'LogisticRegression'
    svm:
        - 'SVR'
    kernel_ridge:
        - 'KernelRidge'
train_test_split:
    test_size: 0.3
    random_state: 66